export enum Target {
    ACCOUNTS = 'ACCOUNTS',
    CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
    BOXES = 'BOXES',
    CURRENT_BOX = 'CURRENT_BOX',
    MESSAGES = 'MESSAGES',
    CURRENT_MESSAGE = 'CURRENT_MESSAGE',
    FETCH_MORE_MESSAGES = 'FETCH_MORE_MESSAGES'
}
